### ISSUE TITLE
Customize default date range on Grafana to course start and end dates

### ISSUE THREAD

**Issue by quitterie-lcs** [openfun/potsie#55]
## Feature Request

By default, the date range on Grafana is set to 90 days. It is one of the possible value to set with Grafana (the default value can be set with a string giving a number of days). But in practice, with pedagogical teams, it would be more confortable and meaningful to get the default date range with start and end dates of the course session. 

It means that the date range should be computed from these two days. But this requires more investigation on what is possible with Grafana

**Comment by jmaupetit** [comment]
Can we have a dashboard giving a teacher's courses overview? With clickable links to each "Course videos overview" dashboard, we would have an easy way to set analysis time span. WDYT?

**Comment by quitterie-lcs** [comment]
That would be a good idea. It would be the teacher's home dashboard.
When accessing a course dashboard, the start and end date would be also transmitted, is that what you mean ?

**Comment by jmaupetit** [comment]
> That would be a good idea. It would be the teacher's home dashboard.

You read my mind.

>  When accessing a course dashboard, the start and end date would be also transmitted, is that what you mean ?

Yes, precisely. :wink:
